#!/usr/bin/env python3
"""
simulation_engine.py  —  Layer 4 (Monte Carlo Scenario Engine)

Builds the scenario table that Layers 5/6/7 consume. It does NOT re-fetch any
market data: every input comes from existing handoffs / persisted artifacts.

METHOD SELECTION  (mirrors the covariance estimation's Method A / Method B split)
--------------------------------------------------------------------------------
The engine reads module 0's `use_factor_covariance` flag from factor_history.json
— the SAME flag that switches the covariance estimator:

  * Method A  (use_factor_covariance == False, the DEFAULT/realistic path):
        ALL assets have >= 36 months of history. Scenarios are generated by
        BOOTSTRAPPING real monthly history (not factor decomposition), so the
        simulated risk matches the realized (Ledoit-Wolf) risk by construction.

  * Method B  (use_factor_covariance == True, FALLBACK only):
        SOME asset has < 36 months. Scenarios use the factor decomposition
        (shared factor draw + per-asset residuals), corrected so its means are
        sane (de-meaned factor draws, zero-mean residuals, re-centered on the
        factor-model expected return).

Both paths re-center every asset on its factor-model expected return capm_mu/12
(from the "CAPM Returns" sheet), so the simulated arithmetic-annualized mean
equals the factor-model return rather than an inflated historical/residual mean.

INPUTS (read-only):
  - returns_stats.xlsx
        "LongRun Monthly Returns" : historical monthly returns matrix (Method A
                                    bootstrap source; same data Ledoit-Wolf and the
                                    resampling wrapper use).
        "CAPM Returns"            : factor-model expected returns capm_mu (re-center).
        "Annualised Cov"          : Ledoit-Wolf Sigma (yardstick in verification).
  - factor_history.json   (Module 0): use_factor_covariance flag; per-market factor
                                       returns + monthly RF (Method B).
  - factor_residuals.json (Module 1 / Part A): per-asset category betas, residual
                                       shock pool, residual variance, factor cov F
                                       (Method B); also the canonical asset list.

OUTPUT (interface UNCHANGED — Layers 5/6/7 are untouched):
  - simulated_returns.npz  with keys: returns (S x n monthly total returns),
    tickers, n_scenarios, random_seed.

Run standalone for verification (shape, per-asset stats, and a consistency check
of the simulated distribution against the method-appropriate yardstick).
"""

import json
import os
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ── Configuration ──────────────────────────────────────────────────────────────
SCRIPT_DIR            = os.path.dirname(os.path.abspath(__file__))
FACTOR_HISTORY_PATH   = os.path.join(SCRIPT_DIR, "factor_history.json")
FACTOR_RESIDUALS_PATH = os.path.join(SCRIPT_DIR, "factor_residuals.json")
RETURNS_STATS_PATH    = os.path.join(SCRIPT_DIR, "returns_stats.xlsx")
SIM_OUTPUT_PATH       = os.path.join(SCRIPT_DIR, "simulated_returns.npz")
N_SCENARIOS           = 10_000


# ── Handoff loading ─────────────────────────────────────────────────────────────

def _load_handoffs(history_path=FACTOR_HISTORY_PATH, residuals_path=FACTOR_RESIDUALS_PATH):
    """Load the Module 0 and Part A handoffs (raises if either is missing)."""
    with open(history_path, encoding="utf-8") as f:
        history = json.load(f)
    with open(residuals_path, encoding="utf-8") as f:
        residuals = json.load(f)
    return history, residuals


def _load_use_factor_flag(path=FACTOR_HISTORY_PATH, default=False):
    """
    module 0's use_factor_covariance flag (same flag the covariance estimator uses).
    True  -> some asset has < 36 months -> Method B (factor decomposition).
    False -> all assets have full history -> Method A (bootstrap). DEFAULT.
    """
    try:
        with open(path, encoding="utf-8") as f:
            return bool(json.load(f).get("use_factor_covariance", default))
    except Exception:
        return default


def _load_capm_mu_monthly(tickers, path=RETURNS_STATS_PATH):
    """Factor-model expected returns capm_mu / 12 (monthly), aligned to `tickers`."""
    capm = pd.read_excel(path, sheet_name="CAPM Returns")
    m = dict(zip(capm["Ticker"].astype(str), capm["CAPM_Expected_Return"].astype(float)))
    missing = [t for t in tickers if t not in m]
    if missing:
        print(f"  WARNING: no CAPM return for {missing}; re-centering those on 0.")
    return np.array([m.get(t, 0.0) / 12.0 for t in tickers], dtype=float)


def _load_longrun(tickers, path=RETURNS_STATS_PATH):
    """Historical monthly returns matrix (M x n) aligned to `tickers` (Method A)."""
    lr = pd.read_excel(path, sheet_name="LongRun Monthly Returns", index_col=0)
    missing = [t for t in tickers if t not in lr.columns]
    if missing:
        raise KeyError(f"'LongRun Monthly Returns' is missing columns {missing}; "
                       "cannot bootstrap (Method A). Re-run module1_data.py.")
    return lr[list(tickers)].astype(float)


def _market_factor_arrays(history, market):
    """(factor_names, factor_matrix (M x nf), rf_vector (M,)) for a market."""
    md = history["markets"][market]
    names = [c for c in md["columns"] if c != "RF"]
    factor_matrix = np.column_stack([np.asarray(md["factor_returns"][c], dtype=float)
                                     for c in names])
    rf_vector = np.asarray(md["monthly_rf"], dtype=float)
    return names, factor_matrix, rf_vector


# ── Method A: bootstrap real history (de-mean + re-center) ──────────────────────

def _simulate_method_a(tickers, S, rng, capm_monthly, verbose=True):
    """
    Bootstrap whole historical months (with replacement) so contemporaneous
    cross-asset correlations and fat tails are preserved; de-mean each asset by its
    own historical mean (shocks only); re-center on the factor-model mean capm_mu/12.

      total[s, i] = hist[k_s, i] - hist_mean[i] + capm_monthly[i]

    `k_s` is shared across assets within a scenario (the whole-row resample).
    """
    H = _load_longrun(tickers).to_numpy(dtype=float)        # M x n
    M = H.shape[0]
    hist_mean = H.mean(axis=0)                               # (n,)

    k = rng.integers(0, M, size=S)                           # one row per scenario
    drawn = H[k]                                             # (S, n), correlations intact
    total = drawn - hist_mean + capm_monthly                # de-mean then re-center
    if verbose:
        print(f"  Method A (bootstrap): resampled {S} of {M} historical months "
              f"per asset; de-meaned and re-centered on capm_mu/12.")
    return total


# ── Method B: factor decomposition (corrected means) ────────────────────────────

def _simulate_method_b(tickers, S, rng, capm_monthly, history, residuals, verbose=True):
    """
    Shared factor draw + per-asset residuals, with the three mean corrections:
      * factor draws DE-MEANED (shocks only, not their historical averages),
      * residual draws ZERO-MEANED,
      * each scenario RE-CENTERED on the factor-model expected return capm_mu/12.

      total[s, i] = capm_monthly[i] + (factor_shock[s] . beta_i) + resid0[s, i]
    """
    assets = residuals["assets"]
    n = len(tickers)
    col_of = {t: i for i, t in enumerate(tickers)}

    markets = {}
    for t in tickers:
        markets.setdefault(assets[t]["market"], []).append(t)
    if len(markets) > 1 and verbose:
        print(f"  NOTE: mixed-market portfolio {sorted(markets)} -- deferred stopgap: "
              "independent per-market factor-month draws (no cross-market alignment).")

    total = np.empty((S, n), dtype=float)
    for market, mkt_tickers in markets.items():
        names, factor_matrix, _rf = _market_factor_arrays(history, market)
        M = factor_matrix.shape[0]
        factor_mean = factor_matrix.mean(axis=0)             # de-mean the factor draws

        k = rng.integers(0, M, size=S)                       # ONE shared draw per market
        factor_shocks = factor_matrix[k] - factor_mean       # (S, nf), zero-mean

        B = np.array([[float(assets[t]["betas"].get(f, 0.0)) for f in names]
                      for t in mkt_tickers])                 # (n_mkt, nf)
        systematic = factor_shocks @ B.T                     # (S, n_mkt), zero-mean

        for j, t in enumerate(mkt_tickers):
            pool = np.asarray(assets[t]["residual_shocks"], dtype=float)
            if pool.size == 0:
                resid = np.zeros(S)
            else:
                draw = pool[rng.integers(0, pool.size, size=S)]
                resid = draw - pool.mean()                   # zero-mean residual draw
            i = col_of[t]
            total[:, i] = capm_monthly[i] + systematic[:, j] + resid

    if verbose:
        print(f"  Method B (factor decomposition): de-meaned factor draws + zero-mean "
              f"residuals, re-centered on capm_mu/12.")
    return total


# ── Simulation engine (public; interface unchanged) ─────────────────────────────

def simulate_scenarios(tickers=None, n_scenarios=N_SCENARIOS, random_seed=None,
                       history=None, residuals=None, persist=True, verbose=True,
                       method=None):
    """
    Build the (n_scenarios x n_assets) table of simulated monthly total returns,
    dispatching on the Method A / Method B flag. Output (npz keys) is unchanged.

    method : optional override ("A" or "B"); default reads use_factor_covariance.
    """
    if history is None or residuals is None:
        history, residuals = _load_handoffs()

    assets = residuals["assets"]
    if tickers is None:
        tickers = list(assets.keys())
    missing = [t for t in tickers if t not in assets]
    if missing:
        raise KeyError(f"Tickers not in Part A handoff (re-run module1): {missing}")

    rng = np.random.default_rng(random_seed)
    S   = int(n_scenarios)
    n   = len(tickers)

    if method is None:
        method = "B" if _load_use_factor_flag() else "A"
    method = method.upper()

    capm_monthly = _load_capm_mu_monthly(tickers)

    if verbose:
        flag = _load_use_factor_flag()
        print(f"  use_factor_covariance = {flag}  ->  Method {method} "
              f"({'factor decomposition' if method == 'B' else 'bootstrap real history'})")

    if method == "A":
        total = _simulate_method_a(tickers, S, rng, capm_monthly, verbose)
    else:
        total = _simulate_method_b(tickers, S, rng, capm_monthly,
                                   history, residuals, verbose)

    df = pd.DataFrame(total, columns=tickers)
    df.index.name = "scenario"

    if persist:
        np.savez_compressed(
            SIM_OUTPUT_PATH,
            returns=total,
            tickers=np.array(tickers, dtype=object),
            n_scenarios=S,
            random_seed=(-1 if random_seed is None else random_seed),
        )
        if verbose:
            print(f"  Persisted -> {SIM_OUTPUT_PATH}  ({S} x {n})")

    return df


# ── Yardsticks for verification ─────────────────────────────────────────────────

def factor_model_covariance(tickers, residuals=None):
    """
    Factor-model MONTHLY covariance B F Bᵀ + D from Part A inputs (the by-construction
    yardstick for Method B). Cross-market pairs are 0; diagonal adds residual variance.
    """
    if residuals is None:
        _, residuals = _load_handoffs()
    assets = residuals["assets"]
    fcov   = residuals["factor_covariance"]
    F_by_market = {m: (v["factors"], np.array(v["matrix"], dtype=float))
                   for m, v in fcov.items()}

    n = len(tickers)
    sigma = np.zeros((n, n))
    for i, ti in enumerate(tickers):
        mi = assets[ti]["market"]
        names_i, Fi = F_by_market[mi]
        bi = np.array([float(assets[ti]["betas"].get(f, 0.0)) for f in names_i])
        for j, tj in enumerate(tickers):
            if assets[tj]["market"] != mi:
                continue
            bj = np.array([float(assets[tj]["betas"].get(f, 0.0)) for f in names_i])
            sigma[i, j] = bi @ Fi @ bj
        rv = assets[ti]["residual_variance"]
        sigma[i, i] += float(rv) if rv is not None else 0.0
    return pd.DataFrame(sigma, index=tickers, columns=tickers)


def ledoit_wolf_monthly_covariance(tickers, path=RETURNS_STATS_PATH):
    """The optimizer's Ledoit-Wolf covariance ('Annualised Cov') de-annualized to
    MONTHLY (/12) — the by-construction yardstick for Method A."""
    cov = pd.read_excel(path, sheet_name="Annualised Cov", index_col=0)
    return cov.loc[list(tickers), list(tickers)].astype(float) / 12.0


# ── Verification ────────────────────────────────────────────────────────────────

def _verify(tickers=None, seed=12345):
    W = 78
    history, residuals = _load_handoffs()
    if tickers is None:
        tickers = list(residuals["assets"].keys())

    method = "B" if _load_use_factor_flag() else "A"
    markets = sorted({residuals["assets"][t]["market"] for t in tickers})
    print(f"\n{'='*W}")
    print("  Layer 4 -- Monte Carlo Scenario Engine  (VERIFICATION)")
    print(f"  Assets   : {', '.join(tickers)}")
    print(f"  Market(s): {', '.join(markets)}   |   Scenarios: {N_SCENARIOS}   |   seed={seed}")
    print(f"  Method   : {method}  "
          f"({'bootstrap real history' if method == 'A' else 'factor decomposition'})")
    print(f"{'='*W}")

    sim = simulate_scenarios(tickers, n_scenarios=N_SCENARIOS, random_seed=seed,
                             history=history, residuals=residuals)

    print(f"\n  Matrix shape : {sim.shape}   (expected {N_SCENARIOS} x {len(tickers)})")

    capm_monthly = _load_capm_mu_monthly(tickers)

    # Per-asset: simulated mean vs factor-model target; simulated vol vs LW vol.
    lw_monthly = ledoit_wolf_monthly_covariance(tickers)
    lw_vol_ann = np.sqrt(np.diag(lw_monthly.values)) * np.sqrt(12)

    print(f"\n  Per-asset checks (annualized %):")
    print(f"    {'Ticker':<14}{'simMean':>10}{'capm_mu':>10}{'simVol':>10}{'LW vol':>10}"
          f"{'volErr%':>9}")
    print(f"    {'-'*14}{'-'*10}{'-'*10}{'-'*10}{'-'*10}{'-'*9}")
    for i, t in enumerate(tickers):
        col = sim[t].values
        sim_mean_ann = col.mean() * 12
        sim_vol_ann  = col.std(ddof=0) * np.sqrt(12)
        capm_ann     = capm_monthly[i] * 12
        err = 100.0 * (sim_vol_ann - lw_vol_ann[i]) / lw_vol_ann[i] if lw_vol_ann[i] else float("nan")
        print(f"    {t:<14}{sim_mean_ann*100:>10.1f}{capm_ann*100:>10.1f}"
              f"{sim_vol_ann*100:>10.1f}{lw_vol_ann[i]*100:>10.1f}{err:>9.1f}")

    # Covariance consistency vs the method-appropriate yardstick.
    sim_cov = sim.cov()
    if method == "A":
        model = lw_monthly
        label = "Ledoit-Wolf monthly ('Annualised Cov' / 12)"
    else:
        model = factor_model_covariance(tickers, residuals)
        label = "factor model B F B^T + D"

    print(f"\n  COVARIANCE consistency -- simulated vs {label}")
    max_abs = float(np.abs(sim_cov.values - model.values).max())
    denom   = np.maximum(np.abs(model.values), 1e-12)
    max_rel = float((np.abs(sim_cov.values - model.values) / denom).max())
    print(f"    Max |sim - model| entry : {max_abs:.6e}")
    print(f"    Max relative difference : {max_rel*100:.2f}%   "
          "(expect small -- sampling error over 10,000 draws)")
    print(f"{'='*W}\n")


def main():
    _verify()


if __name__ == "__main__":
    main()
